 version: "3.3"

 services:
   api-students:
     build: ./api-students
     image: mauriciosalazarh/api-students
     ports:
       - 8000:8000
   websimple:
     build: ./websimple
     image: mauriciosalazarh/websimple
     ports:
       - 8080:80
   webbonita:
     build: ./salient
     image: mauriciosalazarh/salient 
     ports:
       - 8081:80
